whitelist:
  - url: "https://www.philenews.com/tag/vouleftikes-ekloges/"
  - url: "https://www.philenews.com/politiki/"
  - url: "https://www.philenews.com/politiki/paraskinio/"
  - url: "https://www.philenews.com/tag/politiki-sinentefxi/"
  - url: "https://www.politis.com.cy/politis-news/politiki"
  - url: "https://www.politis.com.cy/apopseis/stiles"
  - url: "https://www.politis.com.cy/apopseis/analyseis"
  - url: "https://www.reporter.com.cy/categories/topikes-eideseis"
  - url: "https://www.offsite.com.cy/o-efetis"
  - url: "https://www.kathimerini.com.cy/gr/politiki"

item_selector: "a[href]"
title_selector: "h2, h3, a"
allow_path_regex: "/(politiki|vouleftike|politik|politikí|apopseis|politics|eklog|anal(ysi|is))"
required_keywords_any: []
negative_keywords_any: ["video", "sports", "lifestyle", "celebrit", "gallery"]

filters:
  same_day_only: true
